### PR TITLE
Update GMaps.js to 0.4.21. Remove `index.js`.

### PR DESCRIPTION
**Pull request by jibiel**

### CODE REVIEW

**Comment by jibiel** [comment]
@xenda @alvaropereyra Is this club private?

**Comment by jibiel** [comment]
@xenda Thanks! Could you please also release new gem version when you have time?

**Comment by jibiel** [comment]
@alvaropereyra  Could you please release new gem version?

**Comment by xenda** [comment]
Just did!

**Comment by jibiel** [comment]
@xenda Thanks a bunch!

**Comment by jibiel** [comment]
@xenda It seems that I broke some things with my curiosity towards `index.js`. I've created #6 to fix that. 

If you _have_ to keep `gmapsjs.js` in the additional folder for some reason — `app/assets/javascripts/`**gmapsjs**`/gmapsjs.js`, then you could revert last commit of this PR, if not — #6 will do.

**Pull request merged**
